In [15]:
import numpy as np 
a=np.array([1,2,3])# intializing its an 1d array 
b= np.array([[1,2,3,4],[5,6,7,8]])# 2d array
print(a)
print(b)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#to get dimension of the array 
print(a.ndim)
print(b.ndim)
# to get shape of the array we used 
print(f"the shape of the array b is {b.shape}")


1
2
the shape of the array b is (2, 4)


In [17]:
#can chage the default datatype stored in the array and even ca check what type of array is stored 
c=np.array([5.0,6.1,3.1,2.3,54,])
print("the original datatype stored ",c.dtype)
c=np.array([5.0,6.1,3.1,2.3,54],dtype="float16")
print("the new one is ",c.dtype)

the original datatype stored  float64
the new one is  float16


In [18]:
#conversion of a particular array datatype into another 
d=np.array([1.35,2.35,6.35,5.35])
print(d)
print("the original type of array d is ",d.dtype)
d1=d.astype(int) # we use as type to get  convert the dataype pass the type in which you want your array to be stored as 
print("the updated type of array d is ",d1.dtype)
print(d1)

[1.35 2.35 6.35 5.35]
the original type of array d is  float64
the updated type of array d is  int64
[1 2 6 5]


MATHEMATICAL OPERATIONS ON NUMPY 

we ca use all the artihmetic operation which we study in python + - * / ** // % in the numpy for operations on array 

In [19]:
arr=np.array([10,20,30,40])
print(arr+5)#add +5 to each element of array 
print(arr-5)#subtract -5 from each 
print(arr*10)#multiply 10
print(arr**2)# raised to power of 2 

[15 25 35 45]
[ 5 15 25 35]
[100 200 300 400]
[ 100  400  900 1600]


AGGREATION FUNCTIONS IN NUMPY (mean,variance,maximum, minimum,sd,sum)

In [20]:
array=np.array([10,20,30,40,50,60])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr)) # std used to calculate standard deviation in the data 
print(np.var(arr))# var is used to claculate variance in the data 
print(np.max(arr))
print(np.min(arr))


100
25.0
25.0
11.180339887498949
125.0
40
10


INDEXING IN NUMPY 
 
 okay so to acess any element in the array we go like or follows the syntax  ARRAY[ row,column ] (2d array )

for 3d array its like Array[depth ,row ,column]
 
in mumpy it starts from zeroth (0 row and 0 column ) 

In [21]:
arr=np.array([[1,2,3,78,],
              [1,5,4,89]])
print(arr)
# if i want to access the element 78 we can easily do it by indexing 
print(arr[0,3]) #or 
print (arr[0,-1]) # as in numpy you can perform both +ve and -ve indexing 


[[ 1  2  3 78]
 [ 1  5  4 89]]
78
78


SLICINING IN NUMPY

slicing is done to get a particular grp of element  

syntax for slicing i s as simple of indexing but there is a diff 

Syntax :- arr[starts : stop : step ]

In [22]:
arr= np.array([[1,2,3,4],
              [4,8,9,10],
               [10,12,13,14] ])
print(arr)
print(arr[0,:]) #gives you  elemnts of zeroth row 
print(arr[:,2]) # to get a specific column like 2 
 # if want to acess the  elemnts from row 1 but not all of them 
print(arr[1,2:4] ) #where 1 is the row 2 is the start index and 4 is the stop index 
print(arr[0:-1,2]) # to access elements of column 2 first of all we do (indexing of start:stop ) then column no 


[[ 1  2  3  4]
 [ 4  8  9 10]
 [10 12 13 14]]
[1 2 3 4]
[ 3  9 13]
[ 9 10]
[3 9]


BOOLEAN MASKING 

done in the case to get element under specific conditions 


In [23]:
arr= np.array([[1,2,3,4],
              [4,8,9,10],
               [10,12,13,14] ])
print(arr[arr>5])# print al the  elemts above 5 
print(arr[0,arr[0]>5])
print(arr[arr[:,0]>5,0])

[ 8  9 10 10 12 13 14]
[]
[10]


ARRAY RE SHAPING (used to convert 1d array into multi dimensional )


In [24]:
# A NORMAL SYNATAX FOR REHAPING IN WHICH WE PASSESS ROWS AND COLUMNS 
arr=np.array([1,2,3,4])
arr1=arr.reshape(2,2)
print(arr1)  

[[1 2]
 [3 4]]


FLATTENING (used to conver 2d,3d array into 1d)

here we have 2 methods :-

1) Ravel:- used when to do work in inplace=true means there is no copy of original array created 

2) Flatten :- creates a copy of original array and then do changes in original array 

In [25]:
arr=np.array([[45,35,65,25],[45,25,31,96,]])
print(arr.flatten())
print(arr.ravel())

[45 35 65 25 45 25 31 96]
[45 35 65 25 45 25 31 96]


INSERTION ,APPEND ,CONCATENATE ,DELETE IN ARRAY 

so its simple all of them have almost same syntax for example :-

np.insert(array,index,value,axis=0,1)

np.append(array, value, axis=0,1)

np.concatenate((array1,array2),axis=0,1) 

np.delete(array,index,axis=0,1)

np.vstack((arr1,arr2))  if want to vertical stack only 1 array then np.vstack(arr1)

np.hstack((arr1,arr2)) if want to horizontally stack only 1 array then np.hstack(arr2)

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[4,5,6]])
print(np.insert(arr1,1,10,axis=0))
print(np.append(arr1,[[10,10,10]],axis=0))
print(np.delete(arr1,1,axis=0))
print(np.concatenate((arr1,arr2),axis=0))
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))



BROADCASTING AND VECTORIZATION

broadcasting and vectorizations are used to  do mathematcal calulations on array so that we can avoid using loops hence we  used methods of 

broadcasting and vectorization as they are faster and easy to apply on arrays instead loops are complicated 

In [ ]:
'''let us take an example where we have taken a list of price of grocerry items and now we want new list after applying 10 percent discount on items price 
so we use loops in normal python but loops are slow in large datasets so to  avoid such problems we use broadcasting in broadcasting we apply direct arithmetic operations on 
array 
'''
arr=np.array([1,2,3])
arr1=np.array([1,2,3])
result =arr+10# so in broadcasting what it does numpy  thinks 10 also an array so same dimension and shape  and adds it to the arr forming result 

[2 4 6]
[11 12 13]


NAN VALUES ,INFINITE VALUES 

NAN  stands for not a number so to check wether there exist nan values in the array or not we use np.isnan , to check infinte values we use np.isinfand to repalce 

NAN values with a no we use np.nan_to_num(array,nan=value )

OKAY SO THIS IS END OF NUMPY 

HOPE YOU GUS LIKED IT AND ABLE TO LEARN AND IMPLEMENT IN THE MACHINE LEARNING 

**AARE JA KHA RAHE HO YA TEST TO H DEKAR JAYO TABHI MANUNGA KI NUMPY AATI HAI** 


🧠 NumPy Challenge: Grocery Sales Data Analysis
You're given a NumPy array of 7 days of grocery sales.
Each row represents a day, and each column represents an item.

python
Copy
Edit
import numpy as np

# Dataset: Rows = Days (7), Columns = Items (5)
sales_data = np.array([
    [20, 34, 30, 21, 18],  # Day 1

    [22, 30, 35, 20, 19],  # Day 2

    [19, 29, 32, 25, 20],  # Day 3
    
    [25, 33, 31, 23, 21],  # Day 4
    
    [18, 27, 28, 22, 17],  # Day 5
    
    [24, 31, 29, 26, 23],  # Day 6
    
    [21, 35, 34, 24, 22],  # Day 7
    
])
Your Tasks:
Total sales per item → Column-wise sum.

Average sales per day → Row-wise mean.

Find the day number (1-indexed) with maximum total sales.

Find the item number (1-indexed) with minimum total sales.

Replace all values < 20 with 20 in a copy of the array.

Create a new array with a 10% discount on Day 3's sales only.

Extract sales of Item 2 and Item 4 from even-numbered days only (Day 2, 4, 6).

In [61]:
import numpy as np

# Dataset: Rows = Days (7), Columns = Items (5)
sales_data = np.array([
    [20, 34, 30, 21, 18],  # Day 1
    [22, 30, 35, 20, 19],  # Day 2
    [19, 29, 32, 25, 20],  # Day 3
    [25, 33, 31, 23, 21],  # Day 4
    [18, 27, 28, 22, 17],  # Day 5
    [24, 31, 29, 26, 23],  # Day 6
    [21, 35, 34, 24, 22],  # Day 7
])


#task 1 
print(np.sum(sales_data,axis=0))
#task2
print(np.mean(sales_data,axis=1))
#task3
highest_arr=np.sum(sales_data,axis=1)
position=np.argmax(highest_arr)
print("highest sales were on day ",position +1)
#task 4
total_sale_item=np.sum(sales_data,axis=0)
position=np.argmin(total_sale_item)
print("item no with lowest sale = ",position +1)
#task5
sales_modified = sales_data.copy()
sales_modified[sales_modified < 20] = 20
print(sales_modified)

# task 6
day3_sales = sales_data[2]  # Day 3 is index 2
discounted_day3 = day3_sales * 0.90
print(discounted_day3)
# task 7
print(sales_data[1:7:2,1])
print(sales_data[1:7:2,3])


[149 219 219 161 140]
[24.6 25.2 25.  26.6 22.4 26.6 27.2]
highest sales were on day  7
item no with lowest sale =  5
[[20 34 30 21 20]
 [22 30 35 20 20]
 [20 29 32 25 20]
 [25 33 31 23 21]
 [20 27 28 22 20]
 [24 31 29 26 23]
 [21 35 34 24 22]]
[17.1 26.1 28.8 22.5 18. ]
[30 33 31]
[20 23 26]
